### ISSUE TITLE
Feature Request: #anchor to link a specific template

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#10]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
User 1 asks for the 'example' template.
User 2 sends them this: http://ps.ss13.net/#example
User 1 clicks the link. The page loads and brings up the 'example' template.

**Describe alternatives you've considered**
Option 1: The anchor is to '#department/example' and opens the template at templates/department/example.txt
Option 2: The anchor is to '#example' and there exists some way to map that to the correct path.

**Additional context**

**Comment by soryy708** [comment]
So... a way to add links to pencode?

**Comment by Dibasic** [comment]
Implemented via 711cd491606d01ed00de89a2a65da6017c8c18c1
