### ISSUE TITLE
Feature Request: Insert basic pencode blocks

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#11]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The user has access to a new control in the top fieldset, a selectmenu which when an item is chosen from its menu will insert a commonly used block of pencode at the cursor. Commonly used blocks might be: [grid] (prompt for rows/columns), [table] (same), paperwork header with centered title and logo, etc.

**Describe alternatives you've considered**
These blocks could be stored in a global JS list, stored in a .json file and accessed when needed, loaded after startup and then available as a global list, or stored as an element somewhere.

**Additional context**
Adding this control as a <select> inside the top fieldset will apply jQuery UI selectmenu styling with our color scheme already applied.

**Comment by soryy708** [comment]
So, buttons for inserting rich formatting? Something like what [TinyMCE](https://www.tiny.cloud/) does?

**Comment by Dibasic** [comment]
A little more like the editor on an old bbcode forum, or in the comment box here actually, where clicking the buttons to add formatting just adds the code for that formatting to your input textbox instead of showing you formatted text in the input.

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/22
