### ISSUE TITLE
Feature Request: Migrate from raw CSS to Sass

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#16]
**Is your feature request related to a problem? Please describe.**
Raw CSS is limiting and bloated. Sass can be used for dev convenience, which is then compiled to CSS.

**Describe the solution you'd like**
https://sass-lang.com/

**Describe alternatives you've considered**
... Or don't use Sass. That's fine too.

**Additional context**
https://sass-lang.com/

**Comment by Dibasic** [comment]
May consider this in the future, but I've decided it's more important to keep this simple for now to allow more content contributions.
