### ISSUE TITLE
Feature Request: Set up linter rules

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#17]
**Is your feature request related to a problem? Please describe.**
JS, due to its dynamic nature, tends to fail in production. Currently there's no way to know if the JS code is problemantic other than running it manually.

**Describe the solution you'd like**
Set up linter rules. Linting is a form of static code analysis that allows you to see potential issues with your code before it's run.

**Describe alternatives you've considered**
Or dont.

**Additional context**
https://eslint.org/

**Comment by Dibasic** [comment]
Will look into doing this.
