### ISSUE TITLE
Feature Request: Set up a transpiler (babel)

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#18]
**Is your feature request related to a problem? Please describe.**
Writing backwards-compatible JavaScript is a pain, especially when considering how old browsers can get. ES6 is very fun.

**Describe the solution you'd like**
Set up a transpiler like Babel to turn valid modern JS in to backwards compatible old-style JS automatically.

**Describe alternatives you've considered**
Or not.

**Additional context**
https://babeljs.io/

**Comment by Dibasic** [comment]
May consider this in the future, but I've decided it's more important to keep this simple for now to allow more content contributions.
