### ISSUE TITLE
Link in repository description looks wrong

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#20]
**Describe the bug**
Description links to ` https://dibasic.github.io/SS13Paperwo...`

**To Reproduce**
1. Go to https://github.com/Dibasic/SS13PaperworkSimulator

**Expected behavior**
Should link to `http://ps.ss13.net/`

**Web Browser (please complete the following information):**
Irrelevant

**Screenshots**
![image](https://user-images.githubusercontent.com/2157782/53910320-3876f600-405c-11e9-832f-39a2840d972d.png)

**Pen Code**
Irrelevant

**Additional context**
Null

**Comment by Dibasic** [comment]
Sure is. Fixed.
