### ISSUE TITLE
Sometimes template loads but preview not updated

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#21]
**Describe the bug**
Sometimes, but not all times, loading a template will result in the left side getting updated but the right side not. Usually happens with templates with a lot of content.

**To Reproduce**
1. Pick a template
2. Press load

**Expected behavior**
Both left and right side get updated

**Web Browser (please complete the following information):**
* Firefox v65.0.2 (64-bit)
* Chrome 72.0.3626.121 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/2157782/54022461-35365400-419b-11e9-9220-796892fca79f.png)

**Pen Code**
N/A

**Additional context**
N/A

**Comment by soryy708** [comment]
Perhaps related to https://github.com/Dibasic/SS13PaperworkSimulator/issues/6 ?

**Comment by soryy708** [comment]
If loading the same template at a later point during the same session, the bug will not happen. Perhaps it only happens when content has to be downloaded from the server? Try clearing your cache to reproduce.

**Comment by soryy708** [comment]
It's only a gut feeling, but perhaps there's a race condition between downloading the content & updating the right side?
If downloading the content is too slow (like if it's being served to you by a far away server), then updating the right side will happen before the new content is loaded.

**Comment by Dibasic** [comment]
That sounds reasonable, but at the end of `loadFile` we should be updating the output anyway by calling `run()`.

Maybe setting a new timeout for `run()` after loading our file would work?

**Comment by Dibasic** [comment]
Actually we already set a timeout during loadFile, wonder if that line is executed before the AJAX finishes up? Maybe move it into the anonymous function just above?
