### ISSUE TITLE
Make a link to & from wiki?

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#23]
* https://wiki.baystation12.net/Guide_to_Paperwork
* https://wiki.baystation12.net/Example_Paperwork

**Comment by Dibasic** [comment]
I'll definitely add links to the wiki in both `README.md` and `templates/instructions.txt`, though I feel it might be a bit too much of a self-promotion to add a link to my project on the wiki. I'll talk with @EcklesFire about this
