### ISSUE TITLE
Template Request: Add all example paperwork from wiki to the templates

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#24]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
One-stop resource for paperwork.

**Describe alternatives you've considered**
Add all templates from here to the wiki.

**Additional context**
N/A

**Comment by Dibasic** [comment]
This will also require an edit to README to attribute those templates to original authors on the wiki (can be as vague as that, afaik).

**Comment by Dibasic** [comment]
The previously mentioned edit is complete, this one is now fair game. Going to post it and see if anyone in the discord wants to start contributing with an easy one, otherwise, I'll get around to it in a day or two.

**Comment by mikomyazaki** [comment]
Part way through this. Will be finished later on today as I'm being called away.

**Comment by Dibasic** [comment]
Was just about to finish this one up, should have self-assigned sooner, sorry.
