### ISSUE TITLE
Needs a more responsible way of mapping templates to the selector

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#4]
I'd suggest adding a .json file to /templates, using $.get() or $.ajax() to read it, and populating the template dropdown with a name that maps to the file name.

**Comment by Dibasic** [comment]
Could just cut all options and optgroups into an HTML file and insert all those options via jquery when the page loads.

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/14
