### ISSUE TITLE
Feature Request: Menu with submenus to make the template selector smaller

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#40]
**Is your feature request related to a problem? Please describe.**
The selectmenu for picking a template is so large that it extends past the bottom of the viewport on most displays.

**Describe the solution you'd like**
The implementation of a jQuery UI menu with submenus:
![image](https://user-images.githubusercontent.com/8954852/54376100-488c6800-4650-11e9-9765-51355560c51a.png)

**Describe alternatives you've considered**
I haven't considered any other solutions.

**Additional context**
https://jqueryui.com/menu/

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/41
