### ISSUE TITLE
[small] and [large] tags stack with and negate each other

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#43]
**Describe the bug**
Each nested `[small]` or `[large]` tag continues to decrease or increase the size of text. This can result in very small or very large text or nested opposite tags cancelling each other out.

**To Reproduce**
1. Enter the example code below into the input textarea.

**Expected behavior**
- Only one level of `[small]` and `[large]` should be possible. There should be no difference between `[small]X[/small]` and `[small][small]X[/small][/small]`.
- `[small]` and `[large]` tags should not negate each other. Instead, text should be the size set by the first tag it's in (text in a large tag should be large, even if that large tag is inside a small tag)

**Web Browser (please complete the following information):**
 - Firefox, Edge
 - Latest versions

**Screenshots**
Ingame:
![image](https://user-images.githubusercontent.com/8954852/54403160-0b01fc00-469d-11e9-9b88-a892608b18b1.png)
![image](https://user-images.githubusercontent.com/8954852/54403534-608ad880-469e-11e9-8c68-8279d3c7ddcf.png)
Simulator:
![image](https://user-images.githubusercontent.com/8954852/54403085-c9715100-469c-11e9-8425-6aecccd1a0eb.png)
![image](https://user-images.githubusercontent.com/8954852/54403553-713b4e80-469e-11e9-827c-aa015145337d.png)

**Pen Code**
`TEST1[small]TEST2[small]TEST3[small]TEST4[/small][/small][/small]`
`TEST1[small]TEST2[large]TEST3[/large]TEST4[/small]TEST5`

**Additional context**
We are using `<small>` and `<large>` tags, while the game uses `<font>`. Fixing this may require some snowflakey checks.

**Comment by soryy708** [comment]
Nah. Just have the font size change to an absolute one, not a relative one.

Instead of turning `[small]` in to `<small>`, turn it in to `<span class="small-text">` where `small-text` will have `font-size` of, say, `12px` or something absolute. Same for `[large]`

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/46
