### ISSUE TITLE
[sign] does not use the correct font

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#45]
If anyone wants to do some digging in [Baystation12/Baystation12](https://github.com/Baystation12/Baystation12), this would be a nice thing to get right.

**Comment by soryy708** [comment]
Might be easier to just ask a dev. They may have it stored in their memory.

**Comment by soryy708** [comment]
I asked a Dev on Discord. Here's what they said:

* Default font: Verdana
* Sign font: Times New Roman
* Crayon font: Comic Sans MS
* Fancy Font: Segoe Script

**Comment by Dibasic** [comment]
What does "fancy font" refer to, do you know?

**Comment by soryy708** [comment]
No idea.
