### ISSUE TITLE
Feature Request: Night Mode

### ISSUE THREAD

**Issue by WatermelonsEverywhere** [Dibasic/SS13PaperworkSimulator#54]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to prepare a template late at night, or I want to use the site to preview something I'm writing and not have to do corrections in-game, but the full-white color scheme really hurts my eyes.
**Describe the solution you'd like**
A button or setting that can turn the color scheme more night-friendly, so my eyes don't hurt.

**Describe alternatives you've considered**
None.

**Additional context**
Just open the site at night, and you'll see what I mean.

**Comment by Dibasic** [comment]
Should it also change the preview's colors? Or should the preview stay faithful to the ingame look?

**Comment by WatermelonsEverywhere** [comment]
I think it should, enabling something like Night Mode already communicates the site will be changed to choose comfort over accuracy, and the user can disable Night Mode, if only to review the general look of the document is correct and then switch back.

**Comment by soryy708** [comment]
Sounds fun. I can do that.

I did a dark themed website before. Note to self: Don't use orange on black. It'll look a lot like a certain website...

**Comment by soryy708** [comment]
May your eyes rest in peace.

https://github.com/Dibasic/SS13PaperworkSimulator/pull/56
