### ISSUE TITLE
Feature Request: Preview setting for pen colors, crayon colors, fancy pen

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#55]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A control added to the Preview Settings menu with two additional select menus:
1. Pen type (pen or crayon)
2. Pen style (see additional context)

These default to a black pen setting.

When changed, the style of the output adjusts based on setting.

**Describe alternatives you've considered**

Instead of offering all ingame colors, we could offer
- just the preset black/red/green/blue, or
- a color picker

The ingame colors may be better to offer, if more restrictive and theoretically a source of maintenance if pencode is ever touched. WYSIWYG, and unless adminbus is involved (or antag pens with a few extra colors), you only get the common colors. There's the rainbow crayon, however, which gets a color picker.

**Additional context**
Pen styles: clerical kit pins have any of these colors, color changing pens have black/red/blue/green, and the fancy pen only has their one color.

- Black (default): 000000
- Red (red pens): FF0000
- Blue (blue pens): 0000FF
- Green (color changing pens): 00FF00
- Pink (clerical kit pen): FF00FF
- Orange (clerical kit pen): FF9900
- Cyan (clerical kit pen): 00FFFF
- Invisible (clerical kit pen): FFFFFF
- Fancy (afaik this only spawns on the Unishi/Verne): 1c1713, Segoe Script font

Crayon styles: Comic Sans MS font; as far as I know, all the same colors as clerical kit pens. The rainbow crayon can pick any color and defaults to FFF000

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/57
