### ISSUE TITLE
Add OCIE logo

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#59]
See @zaredman's recently merged https://github.com/Baystation12/Baystation12/pull/24915

`[ocielogo]`

![](https://raw.githubusercontent.com/Baystation12/Baystation12/dev/html/images/ocielogo.png)

**Comment by soryy708** [comment]
License?

**Comment by Dibasic** [comment]
@soryy708 All images in the Bay repo are CC BY-NC-SA 3.0. Sharealike and attribution are taken care of by LICENSE and README respectively.

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/61
