### ISSUE TITLE
Changing pen color and using a theme can cause text to be unreadable

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#62]
**Describe the bug**
The only unintended behavior here is that changing your pen color back to 'black' locks it at black and isn't overwritten by color schemes.

**To Reproduce**
1. Set pen color to "Blue"
2. Set theme to "Solarized (Dark)"
3. Realize that looks bad, set pen color to "Black" to reset it
4. You now have black on teal instead of the default solarized color.

**Expected behavior**
Combining these features should do one of two things:
1. Lock out the pen color feature entirely while the theme is not default white.
2. Have the 'Black' pen color instead default to the theme's default text color. Rename 'Black' to 'Black (Default)' or similar.

**Web Browser (please complete the following information):**
 - Firefox 65.0.2

**Screenshots**
![image](https://user-images.githubusercontent.com/8954852/54707915-327b1d80-4b10-11e9-8f41-83eaddd78d84.png)

**Pen Code**

**Additional context**

**Comment by soryy708** [comment]
"Invisible" should be white on white, but becomes extra visible on solarized and black.

**Comment by Dibasic** [comment]
This is where custom properties could be nice. Setting '--defaultTextColor' to be black on the default, white on high-contrast, base0 on Solarized, etc should work

**Comment by soryy708** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/--*#Browser_compatibility

**Comment by soryy708** [comment]
Fix was not adequate. https://github.com/Dibasic/SS13PaperworkSimulator/issues/67
