### ISSUE TITLE
Color is not applied recursively

### ISSUE THREAD

**Issue by soryy708** [Dibasic/SS13PaperworkSimulator#67]
**Describe the bug**
Only part of the text color is changed when switching themes

**To Reproduce**
1. Open the instructions template
2. Switch theme
3. Change pen color

**Expected behavior**
All the text is the same color

**Web Browser (please complete the following information):**
Firefox 66.0 (64-bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/2157782/54954024-57c5bc80-4f52-11e9-95c0-e9fc46fb48b4.png)

**Pen Code**

**Additional context**

**Comment by Dibasic** [comment]
It was set recursively but not to the element directly referenced, oops.
