### ISSUE TITLE
Arrest report format is missing a line

### ISSUE THREAD

**Issue by DeadmonWonderland** [Dibasic/SS13PaperworkSimulator#70]
**Describe the bug**
Pen code format for security arrest report is missing a line

**To Reproduce**

Load the security arrest report, scroll down to the BRIG CHIEF MUST STAMP line

**Expected behavior**

https://i.gyazo.com/13a5068b153bac16a713166064a8a034.png

**Web Browser (please complete the following information):**
 - Firefox 
 - 68.0.1

**Screenshots**

https://i.gyazo.com/8554c0c55573af7d19ea66f7ef9f7b60.png

**Pen Code**

[center][solcrest][h1]Arrest Report[/h1][field][/center]
[i]Revision [date] - [time][/i]
[b]Offense/Incident Type: [/b][field]
[b]Location: [/b][field]
[hr][h3]Arrestee Information[/h3]
[small][i](B##-Brigged, ## time, H-Indefinite Hold, C-Court Martial, P-Parole/Probation, V-Verbal Warning)
[table][row][cell][b]Rank[/b][cell][b]Name[/b][cell][b]Position[/b][cell][b]Charge(s)[/b][cell][b]Disposition[/b]
[row][cell][b][field][/b][cell][field][cell][field][cell][field][cell][field]
[/table][/i][/small][br][br][hr][h3]Personnel Involved in Incident[/h3]
[b]Arresting Officer(s): [/b][field][br]
[b]Other Personnel[/b]
[small][i](V-Victim, S-Suspect, W-Witness, M-Missing, A-Arrested, RP-Reporting Person, D-Deceased)[/i][/small][br]
[table][row][cell][b]Rank[/b][cell][b]Name[/b][cell][b]Position[/b][cell][b]Relation[/b]
[row][cell][b][field][/b][cell][field][cell][field][cell][field]
[row][cell][b][field][/b][cell][field][cell][field][cell][field]
[row][cell][b][field][/b][cell][field][cell][field][cell][field]
[row][cell][b][field][/b][cell][field][cell][field][cell][field]
[row][cell][b][field][/b][cell][field][cell][field][cell][field]
[/table][br][br][hr][h3]Booking Checklist[/h3]
[b]Booking Officer: [/b][field][br]
[table][row][cell][b]Escape Risk[/b][cell][field]
[row][cell][b]Suicide Risk[/b][cell][field]
[row][cell][b]Combative[/b][cell][field]
[row][cell][b]Provided Required Medical Treatment[/b][cell][field]
[row][cell][b]Warrant Presented[/b][cell][field]
[row][cell][b]Advised of Rights[/b][cell][field]
[row][cell][b]Prisoner Searched[/b][cell][field]
[row][cell][b]Provided an Opportunity for Statement[/b][cell][field]
[hr][small]BRIG OFFICER MUST STAMP OR SIGN THIS DOCUMENT
ATTACH ALL RELEVANT DOCUMENTS TO THIS ARREST REPORT[/small][hr]

**Additional context**

**Comment by Dibasic** [comment]
2c2321d82077f1252ceb1dbc46de23cfc893e1b1 caused this, pretty obvious mistake. That'll teach me to push to master after putting so much time into making unit tests, lol.
