### ISSUE TITLE
Angle brackets appear as &lt; and &gt; in output.

### ISSUE THREAD

**Issue by Dibasic** [Dibasic/SS13PaperworkSimulator#8]
**Describe the bug**
Angle brackets show up as unrendered &lt; or &gt; in the output.

**To Reproduce**
1. Type the '<' or '>' symbols into the input.

**Expected behavior**
The angle brackets should appear correctly in the output, but html tags such as <script> should not be interpreted.

**Web Browser (please complete the following information):**
 - Chrome, Edge
 - Latest versions

**Screenshots**
![image](https://user-images.githubusercontent.com/8954852/50249136-c703a180-03a2-11e9-8803-6ada5e3cf853.png)

**Pen Code**
\><

**Additional context**
Introduced in 9e14ed1929e9e7c2240fa438b167d135cc325086 to fix #1 . We replace < and > with &lt; and &gt; to avoid html from being interpreted when output is displayed. The fix for this issue needs to make sure that it doesn't reintroduce that problem.

**Comment by soryy708** [comment]
https://github.com/Dibasic/SS13PaperworkSimulator/pull/13
